from corpus_index import IndriAPI
import math
from utils import *
word_list =['nuclear-powered',
 'adopt',
 '71.2',
 'revenues',
 '5.5',
 'globe',
 'movements',
 '296036',
 'be',
 'economists',
 'surface',
 'all',
 'researcher',
 'underside',
 'born',
 'fits',
 'steady',
 '4m',
 'staircase',
 'conditioners',
 'rent',
 'pattern',
 'computers',
 '3.5',
 'aircraft',
 'peking',
 'net',
 'visit',
 'seasons',
 'juan',
 'sector',
 'comedian',
 'top-quality',
 'reason',
 'attracted',
 'stationary',
 'energy',
 'offers',
 'accompanied',
 'table',
 '1886',
 'refusal',
 'protects',
 'release',
 '80',
 'remained',
 'direction',
 'peng',
 'may',
 'constructed']

# word_list = ['gole',
#  'scandinavian',
#  'debilitating',
#  'sleeve',
#  'convergence',
#  'khem',
#  'highest-level',
#  'condoned',
#  'mishap',
#  'editors',
#  'chanted',
#  'finley',
#  'philosophy',
#  'v5.9025-80',
#  'longest-sought',
#  'resumption',
#  'growth.',
#  'berliner',
#  'reporting',
#  'jarred',
#  'juarez',
#  'bergeron',
#  'archival',
#  '430',
#  'defiance',
#  'unknowable',
#  'tardiness',
#  'verses',
#  'studio',
#  'yong-il',
#  'balked',
#  'tsvetan',
#  'unconscious',
#  'tehran',
#  'batch',
#  '0731',
#  'devils',
#  'championship',
#  'power-sharing',
#  'hunger',
#  'abu',
#  'adjusted',
#  'seasonally',
#  'impossible.',
#  'washingtonian',
#  'phoenix',
#  'pedestrians',
#  '30.5',
#  'fungal',
#  'tune']


indri = IndriAPI('E:/qiuchi/index/index_clueweb12')
collection_doc_count = indri.get_collection_doc_count()
idf_dict = {}
mean = 0
for term in word_list:
    term_2 = stem_words(strip_punctuation(term))
    idf = math.log10(collection_doc_count/(indri.get_doc_frequency(term_2)+1))
    idf_dict[term] = idf
    mean = mean+idf

mean = mean /len(idf_dict)
print(mean, idf_dict)
